src/Entity/Donation.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DonationRepository")
 */
class Donation
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $amount;

    /**
     * @ORM\Column(type="text")
     */
    private $FirstName;

    /**
     * @ORM\Column(type="text")
     */
    private $LastName;

    /**
     * @ORM\Column(type="text")
     */
    private $Country;

    /**
     * @ORM\Column(type="text")
     */
    private $City;

    /**
     * @ORM\Column(type="text")
     */
    private $State;

    /**
     * @ORM\Column(type="text")
     */
    private $Code;

    /**
     * @ORM\Column(type="text")
     */
    private $email;

    /**
     * @ORM\Column(type="text")
     */
    private $address;

    /**
     * @ORM\Column(type="text")
     */
    private $phone;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $employer;

    /**
     * @ORM\Column(type="text")
     */
    private $anonymous;

    /**
     * @ORM\Column(type="text")
     */
    private $type;

    /**
     * @ORM\Column(type="text")
     */
    private $certificate;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $accountType;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $accountNumber;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $accountHolder;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $expiryMonth;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $expiryYear;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $cvv;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comments;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAmount(): ?string
    {
        return $this->amount;
    }

    public function setAmount(string $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->FirstName;
    }

    public function setFirstName(string $FirstName): self
    {
        $this->FirstName = $FirstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->LastName;
    }

    public function setLastName(string $LastName): self
    {
        $this->LastName = $LastName;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->Country;
    }

    public function setCountry(string $Country): self
    {
        $this->Country = $Country;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->City;
    }

    public function setCity(string $City): self
    {
        $this->City = $City;

        return $this;
    }

    public function getState(): ?string
    {
        return $this->State;
    }

    public function setState(string $State): self
    {
        $this->State = $State;

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->Code;
    }

    public function setCode(string $Code): self
    {
        $this->Code = $Code;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getEmployer(): ?string
    {
        return $this->employer;
    }

    public function setEmployer(?string $employer): self
    {
        $this->employer = $employer;

        return $this;
    }

    public function getAnonymous(): ?string
    {
        return $this->anonymous;
    }

    public function setAnonymous(string $anonymous): self
    {
        $this->anonymous = $anonymous;

        return $this;
    }

    public function getCertificate(): ?string
    {
        return $this->certificate;
    }

    public function setCertificate(string $certificate): self
    {
        $this->certificate = $certificate;

        return $this;
    }

    public function getType()
    {
        return $this->type;
    }

    public function setType($type)
    {
        $this->type = $type;

        return $this;
    }

    public function getAccountType()
    {
        return $this->accountType;
    }

    public function setAccountType($accountType)
    {
        $this->accountType = $accountType;

        return $this;
    }

    public function getAccountNumber()
    {
        return $this->accountNumber;
    }

    public function setAccountNumber($accountNumber)
    {
        $this->accountNumber = $accountNumber;

        return $this;
    }

    public function getAccountHolder()
    {
        return $this->accountHolder;
    }

    public function setAccountHolder($accountHolder)
    {
        $this->accountHolder = $accountHolder;

        return $this;
    }

    public function getExpiryMonth()
    {
        return $this->expiryMonth;
    }

    public function setExpiryMonth($expiryMonth)
    {
        $this->expiryMonth = $expiryMonth;

        return $this;
    }

    public function getExpiryYear()
    {
        return $this->expiryYear;
    }

    public function setExpiryYear($expiryYear)
    {
        $this->expiryYear = $expiryYear;

        return $this;
    }

    public function getCvv()
    {
        return $this->cvv;
    }

    public function setCvv($cvv)
    {
        $this->cvv = $cvv;

        return $this;
    }

    public function getComments()
    {
        return $this->comments;
    }

    public function setComments($comments)
    {
        $this->comments = $comments;

        return $this;
    }
}

src/Entity/Featured.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FeaturedRepository")
 * @Vich\Uploadable
 */
class Featured
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $text;

    /**
     * @ORM\Column(type="date")
     */
    private $DateCreated;

    /**
     * @ORM\Column(type="text")
     */
    private $LinkType;

    /**
     * @ORM\Column(type="text")
     */
    private $Link;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $image;

    /**
     * @Vich\UploadableField(mapping="images", fileNameProperty="image")
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="datetime")
     * @var \DateTime
     */
    private $updatedAt;

    /**
     * @ORM\Column(type="text")
     */
    private $position;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getDateCreated(): ?\DateTimeInterface
    {
        return $this->DateCreated;
    }

    public function setDateCreated(\DateTimeInterface $DateCreated): self
    {
        $this->DateCreated = $DateCreated;

        return $this;
    }

    public function getLinkType(): ?string
    {
        return $this->LinkType;
    }

    public function setLinkType(string $LinkType): self
    {
        $this->LinkType = $LinkType;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->Link;
    }

    public function setLink(string $Link): self
    {
        $this->Link = $Link;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage($image)
    {
        $this->image = $image;

        return $this;
    }

    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if ($image) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updatedAt = new \DateTime('now');
        }
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getPosition(): ?string
    {
        return $this->position;
    }

    public function setPosition(string $position): self
    {
        $this->position = $position;

        return $this;
    }

}

templates/index/donation-review-certificate.html.twig
{% extends 'base.html.twig' %}
{% block title %}<title>Armenia Tree Project - Donation Review</title>{% endblock %}

{% block body %}
    <!--Single News-->

    <section class="donation-review-page">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <h1>Review Your Donation</h1>
                    <p>Please review your donation details and submit</p>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-6 col-xs-12">
                    <div class="donation-details">
                        <div>
                            <p>Donation</p>
                            <p>Designation</p>
                            <p>Number of Payments</p>
                            <p>Certificate</p>
                            <p>Donor Name</p>
                            <p>Donor E-mail</p>
                            <p>Comments</p>
                            <p>Billing Name</p>
                            <p>Address</p>
                        </div>
                        <div class="donated-user-details">
                            <p>$ {{ donation.amount }}</p>
                            <p>Backyard Nurseries</p>
                            <p>{{ donation.type }}</p>
                            <p>{{ donation.certificate }}</p>
                            <p>{{ donation.firstName }} {{ donation.lastName }}</p>
                            <p>{{ donation.email }}</p>
                            <p>{{ donation.comments }}</p>
                            <p>{{ donation.firstName }} {{ donation.lastName }}</p>
                            <p>{{ donation.address }}, {{ donation.city }}, {{ donation.state }}, {{ donation.code }}, {{ donation.country }}</p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-xs-12">
                    <div class="certificate-image-wrapper">
                        <img src="/img/certificate.png" alt="linkedin">
                        <h2 class="certificate-presented">{{ donation.firstName }} {{ donation.lastName }}</h2>
                        <p class="certification-date">{{ date }}</p>
                    </div>
                    <div class="donate-button-wrapper">
                        <button class="submit-donation">
                            <a href="{{ path('payment', {'id': donation.Id}) }}" class="submit-donation">Donate Now</a>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!--Footer Section-->

    <section class="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                    <ul>
                        <li class="hidden">
                            <a href="#">Glossary</a>
                        </li>

                        <li>
                            <a href="#">Contact Us</a>
                        </li><li>
                            <a href="#">Privacy Policy</a>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                    <ul>
                        <li class="hidden">
                            <a href="#">FAQ</a>
                        </li>
                        <li class="hidden">
                            <a href="#">Terms & Conditions</a>
                        </li>
                    </ul>
                </div>

                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12"></div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <p><span> Armenia Tree Project </span> <br> 400 West Cummings Park <br> Suite 3900, Woburn, MA 01801 USA
                        <br> 617-926-TREE (8733)</p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                    <p class="copyright-text">&copy; Copyright 1994-2019 Armenia Tree Project, a project of Armenian
                        Assembly of America. All Rights Reserved.</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right  social">
                    <p class="hashtag">#GetRooted</p>
                    <a href="https://www.facebook.com/armeniatree">
                        <img src="./img/facebook-logo.svg" alt="facebook">
                    </a>
                    <a href="https://twitter.com/ArmeniaTree">
                        <img src="./img/twitter-logo.svg" alt="twitter">
                    </a>
                    <a href="https://www.instagram.com/armeniatree/">
                        <img src="./img/instagram-logo.svg" alt="instagram">
                    </a>
                    <a href="https://www.youtube.com/user/ArmeniaTreeProject">
                        <img src="./img/youtube.svg" alt="youtube">
                    </a>
                </div>
            </div>
        </div>
    </section>

    <!-- jQuery -->
    <script src="{{ asset('js/jquery.js') }}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{{ asset('js/bootstrap.min.js') }}"></script>

    <!-- Custom Js Files-->
    <script src="{{ asset('js/main.js') }}"></script>

{% endblock %}

templates/index/eco-camp.html.twig
{% extends 'base.html.twig' %}
{% block title %}<title>Armenia Tree Project - Summer Eco Camps</title>{% endblock %}
{% block body %}

    <section class="eco-camps-top-content secondary-pages-top-content" style="background:url('uploads/images/{{ top.Image }}') no-repeat; background-size:cover;">
        <div class="container">
            <div class="row center-aligned-row">
                <div class="col-sm-6">
                    {% autoescape %}
                        {% if lang == 'eng' %}
                            <h1>{{ top.TitleEng|raw }}</h1>
                        {% elseif lang == 'arm' %}
                            <h1>{{ top.TitleArm|raw }}</h1>
                        {% endif %}
                    {% endautoescape %}
                </div>
                <div class="col-sm-6 cover-text">
                    {% autoescape %}
                        {% if lang == 'eng' %}
                            <p>{{ top.TextEng|raw }}</p>
                        {% elseif lang == 'arm' %}
                            <p>{{ top.TextArm|raw }}</p>
                        {% endif %}
                    {% endautoescape %}
                </div>
            </div>
        </div>
    </section>

    <div class="eco-camps-content-wrapper">
        <section class="community-second">
            <div class="container">
                {% for item in content %}
                    {% if item.Position == 'right' %}
                        <div class="row center-aligned-row">
                            <div class="col-md-6 col-xs-12">
                                {% autoescape %}
                                    {% if lang == 'eng' %}
                                        {{ item.TextEng|raw }}
                                    {% elseif lang == 'arm' %}
                                        {{ item.TextArm|raw }}
                                    {% endif %}
                                {% endautoescape %}
                                {% if item.link is not null %}
                                    <button>
                                        {% if lang == 'eng' %}
                                            {{ item.LinkTextEng|raw }}
                                        {% elseif lang == 'arm' %}
                                            {{ item.LinkTextArm|raw }}
                                        {% endif %}
                                    </button>
                                {% endif %}
                            </div>
                            <div class="col-md-6 col-xs-12">
                                <img src="uploads/images/{{ item.Image }}" alt="">
                            </div>
                        </div>
                    {% elseif item.Position == 'left' %}
                        <div class="row center-aligned-row">
                            <div class="col-md-6 col-xs-12">
                                <img src="uploads/images/{{ item.Image }}" alt="">
                            </div>
                            <div class="col-md-6 col-xs-12">
                                {% autoescape %}
                                    {% if lang == 'eng' %}
                                        {{ item.TextEng|raw }}
                                    {% elseif lang == 'arm' %}
                                        {{ item.TextArm|raw }}
                                    {% endif %}
                                {% endautoescape %}
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
        </section>



    </div>




    <!--Footer Section-->

    <section class="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                    <ul>
                        <li class="hidden">
                            <a href="#">Glossary</a>
                        </li>

                        <li>
                            <a href="#">Contact Us</a>
                        </li><li>
                            <a href="#">Privacy Policy</a>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                    <ul>
                        <li class="hidden">
                            <a href="#">FAQ</a>
                        </li>
                        <li class="hidden">
                            <a href="#">Terms & Conditions</a>
                        </li>
                    </ul>
                </div>

                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12"> </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <p> <span> Armenia Tree Project </span> <br> 400 West Cummings Park <br> Suite 3900, Woburn, MA 01801 USA <br> 617-926-TREE (8733)</p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                    <p class="copyright-text">&copy; Copyright 1994-2019 Armenia Tree Project, a project of Armenian Assembly of America. All Rights Reserved.</p>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right  social">
                    <p class="hashtag">#GetRooted</p>
                    <a href="https://www.facebook.com/armeniatree">
                        <img src="./img/facebook-logo.svg" alt="facebook">
                    </a>
                    <a href="https://twitter.com/ArmeniaTree">
                        <img src="./img/twitter-logo.svg" alt="twitter">
                    </a>
                    <a href="https://www.instagram.com/armeniatree/">
                        <img src="./img/instagram-logo.svg" alt="instagram">
                    </a>
                    <a href="https://www.youtube.com/user/ArmeniaTreeProject">
                        <img src="./img/youtube.svg" alt="youtube">
                    </a>
                </div>
            </div>
        </div>
    </section>


    <!-- jQuery -->
    <script src="{{ asset('js/jquery.js') }}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{{ asset('js/bootstrap.min.js') }}"></script>


    <!-- Custom Js Files-->
    <script src="{{ asset('js/main.js') }}"></script>





    </body>
    </html>
    {#<hr>#}
    {#<table>#}
    {#{% for object in pager.currentPageResults %}#}
    {#<tr>#}
    {#<td>{{ object.Title }}</td>#}
    {#<td>{{ object.Text }}</td>#}
    {#</tr>#}
    {#{% endfor %}#}
    {#</table>#}

    {#{% if pager.haveToPaginate %}#}
    {#{{ pagerfanta(pager) }}#}
    {#{% endif %}#}
    {#<hr>#}
{% endblock %}

templates/index/events.html.twig
{% extends 'base.html.twig' %}
{% block title %}<title>Armenia Tree Project - Donation Review</title>{% endblock %}

{% block body %}

    <section class="join-us secondary-pages-top-content" style="background:url('uploads/images/{{ top.Image }}') no-repeat; background-size:cover; background-position: 0;">
        <div class="container">
            <div class="row center-aligned-row">
                <div class="col-sm-6">
                    {% autoescape %}
                        {% if lang == 'eng' %}
                            <h1>{{ top.TitleEng|raw }}</h1>
                        {% elseif lang == 'arm' %}
                            <h1>{{ top.TitleArm|raw }}</h1>
                        {% endif %}
                    {% endautoescape %}
                </div>
                <div class="col-sm-6 cover-text">
                    {% autoescape %}
                        {% if lang == 'eng' %}
                            <p>{{ top.TextEng|raw }}</p>
                        {% elseif lang == 'arm' %}
                            <p>{{ top.TextArm|raw }}</p>
                        {% endif %}
                    {% endautoescape %}
                </div>
            </div>
        </div>
    </section>

<div class="join-us-main-content-wrapper">

    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="events-page-top-bar-wrapper">
                    <div>
                        {{ form_start(form, {'attr': {'class': 'event-search-bar-wrapper'}}) }}
                        <div>
                            <h6>EVENTS IN</h6>
                            {{ form_widget(form.date, {'attr': {'class': 'calendar'}}) }}
                            <div style="color: red;">{{ form_errors(form.date) }} </div>
                        </div>
                        <div>
                            <h6>SEARCH</h6>
                            {{ form_widget(form.title) }}
                            <div style="color: red;">{{ form_errors(form.title) }} </div>
                        </div>
                        <div>
                            <h6>NEAR</h6>
                            {{ form_widget(form.location) }}
                            <div style="color: red;">{{ form_errors(form.location) }} </div>
                        </div>
                        <div>
                            {{ form_widget(form.send, { 'attr': {'class': "find-events"}}) }}
                        </div>
                        {{ form_end(form) }}
                    </div>
                    <div>
                        <h6>VIEW AS</h6>
                        <button class="list-view active-list-view">List</button>
                        <button class="month-view">Month</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="single-events-panels-wrapper">
                    {% for item in events %}
                    <div class="single-event-panel">
                        <div>
                            {% set startDatetimeString = item.start.local %}
                            {% set endDatetimeString = item.end.local %}
                            <h3><span>{{ startDatetimeString|date('l, M d, Y')|upper  }}</span>  |  {{ startDatetimeString|date('h:iA')  }} UNTIL {{ endDatetimeString|date('h:iA') }}</h3>
                            <h4>{{ item.name.text|raw }}</h4>
                            <p>{{ (item.description.text|length > 250 ? item.description.text|slice(0, 250) ~ '…' : item.description.text)  }}</p>
                            <div class="button-and-destination-content-wrapper">
                                <button class="register-for-event"><a href="{{ item.url|raw }}">Register and Learn More</a></button>
                                <p class="event-destination">{{ item.venue.address.city|raw }} {{ item.venue.address.region|raw }}, {{ item.venue.address.country|raw }}</p>
                            </div>
                        </div>
                        <div>
                            {% if item.logo != null %}
                                <img src="{{ item.logo.url }}"  alt="">
                            {% endif %}
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="event-calendar-view-wrapper events-calendar-large" id='calendar'>

                </div>
        </div>
    </div>
</div>





<!--Footer Section-->

<section class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                    <ul>
                        <li class="hidden">
                            <a href="#">Glossary</a>
                        </li>

                        <li>
                            <a href="#">Contact Us</a>
                        </li><li>
                            <a href="#">Privacy Policy</a>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
                    <ul>
                        <li class="hidden">
                            <a href="#">FAQ</a>
                        </li>
                        <li class="hidden">
                            <a href="#">Terms & Conditions</a>
                        </li>
                    </ul>
                </div>

            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12"> </div>
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                <p> <span> Armenia Tree Project </span> <br> 400 West Cummings Park <br> Suite 3900, Woburn, MA 01801 USA <br> 617-926-TREE (8733)</p>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                <p class="copyright-text">&copy; Copyright 1994-2019 Armenia Tree Project, a project of Armenian Assembly of America. All Rights Reserved.</p>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right  social">
                <p class="hashtag">#GetRooted</p>
                <a href="https://www.facebook.com/armeniatree">
                    <img src="./img/facebook-logo.svg" alt="facebook">
                </a>
                <a href="https://twitter.com/ArmeniaTree">
                    <img src="./img/twitter-logo.svg" alt="twitter">
                </a>
                <a href="https://www.instagram.com/armeniatree/">
                    <img src="./img/instagram-logo.svg" alt="instagram">
                </a>
                <a href="https://www.youtube.com/user/ArmeniaTreeProject">
                    <img src="./img/youtube.svg" alt="youtube">
                </a>
            </div>
        </div>
    </div>
</section>


<!-- jQuery -->
<script src="{{ asset('js/jquery.js') }}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{{ asset('js/moment.shim.js') }}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{{ asset('js/bootstrap.min.js') }}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{{ asset('js/pignose.calendar.js') }}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{{ asset('js/fullcalendar.js') }}"></script>

<!-- FullCalendar -->
<script src="{{ asset('js/gcal.js') }}"></script>

<!-- Custom Js Files-->
<script src="{{ asset('js/main.js') }}"></script>

<script src="https://maps.googleapis.com/maps/api/js?sensor=false&libraries=places&language=gb&key=AIzaSyC9IM-dD38CXohXe15-naktRoHKCm9Xmy0"></script>


    <script>
        $(function() {

            $('#calendar').fullCalendar({
                googleCalendarApiKey: 'AIzaSyAMW70pX5RAo8GYOf8PtyWzvUPvuPKkuTw',
                events: {
                    googleCalendarId: 'armtreeproject@gmail.com'
                }
            })

        });
    </script>


<script>
    var input = document.getElementById('form_location');
    var autocomplete = new google.maps.places.Autocomplete(input);
</script>

<script>
    $(function() {
        $('input.calendar').pignoseCalendar({
            multiple: true,
            select: function(date) {
                $('#form_date').val(date[0].format('YYYY-MM-DD')+' to '+date[1].format('YYYY-MM-DD'));
            }
        });
    });
</script>

{% endblock %}